// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuN0IRiPXY2MKJsR8RMT8nbZdFmHLO1Gc',
    appId: '1:135108904136:web:487eed62d836fe299311fd',
    messagingSenderId: '135108904136',
    projectId: 'pro-4dd65',
    authDomain: 'pro-4dd65.firebaseapp.com',
    storageBucket: 'pro-4dd65.appspot.com',
    measurementId: 'G-2J2Y6W2TLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACyX7IZyMXrLvrxsFcdyRxzd_Wz1ZGjw',
    appId: '1:135108904136:android:60fdf9ac34b489679311fd',
    messagingSenderId: '135108904136',
    projectId: 'pro-4dd65',
    storageBucket: 'pro-4dd65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsgUXq1LB97c3mNINyc3xuQqktueBh_0U',
    appId: '1:135108904136:ios:f9c26bec134752da9311fd',
    messagingSenderId: '135108904136',
    projectId: 'pro-4dd65',
    storageBucket: 'pro-4dd65.appspot.com',
    iosBundleId: 'com.example.goSecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsgUXq1LB97c3mNINyc3xuQqktueBh_0U',
    appId: '1:135108904136:ios:466b4ef896ee7c599311fd',
    messagingSenderId: '135108904136',
    projectId: 'pro-4dd65',
    storageBucket: 'pro-4dd65.appspot.com',
    iosBundleId: 'com.example.goSecure.RunnerTests',
  );
}
